### ISSUE TITLE
Installation fails due to dependency

### ISSUE THREAD

**Issue by andypfau** [TitorX/CITIfile#4]
I tried to install the package with Python 3.11.9:

```
install citifile
Collecting citifile
  Downloading CITIfile-0.1.5.tar.gz (2.1 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-7rmvbd4g/citifile_a8d09f5a0a7e44dda60a13af72799846/setup.py", line 2, in <module>
          from CITIfile import __version__, __author__
        File "/tmp/pip-install-7rmvbd4g/citifile_a8d09f5a0a7e44dda60a13af72799846/CITIfile.py", line 2, in <module>
          import xarray as xr
      ModuleNotFoundError: No module named 'xarray'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

However, it works when I install xarray first (`pip install xarray`).

Shouldn't the package be set up such, that PIP is able to install dependencies automatically?

**Comment by andypfau** [comment]
I think `setup.py` lacks a `install_requires=['xarray']`, see <https://python-packaging.readthedocs.io/en/latest/dependencies.html>.

However, I think that nowadays using a `pyproject.toml` is encouraged instead see <https://stackoverflow.com/a/62983901>.

**Comment by andypfau** [comment]
I did an experiment, and it works on my system. I created a new Conda environment, and ran ` python -m pip install -e .` successfully, and running `test.py` gives the expected result. You can find it here: <https://github.com/andypfau/CITIfile/tree/pyproject>.

I followed this recommendation for the dynamic version numbers: <https://stackoverflow.com/a/73058153>.

Any thoughts?

**Comment by andypfau** [comment]
I was able to successfully test the installation in a virtual environment.

Git had a tag for testing, using the same scheme as you use ("v0.1.8" in my experiment) :
```
$ git log --oneline
9eca6af (HEAD -> pyproject, tag: v0.1.8, origin/pyproject) enabed git versioning module
```

I installed it locally (`pip install -e .`), and checked the versions:
```
$ pip freeze
-e git+ssh://git@github.com/andypfau/CITIfile.git@9eca6af9afd5f98e0ceb75826a9d252001b69171#egg=CITIfile
numpy==2.0.1
packaging==24.1
pandas==2.2.2
python-dateutil==2.9.0.post0
pytz==2024.1
six==1.16.0
tzdata==2024.1
xarray==2024.7.0
```

The files are still in my fork: <https://github.com/andypfau/CITIfile/tree/pyproject>. I can create a PR if you want.
